
name: Workflow3

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      deployToProd: { description: 'Deploy To Prod', required: true, type: boolean, default: false }    

jobs:
  Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Stage Step
        run: echo "Deploying to Stage"

  Prod:
    if: ${{ github.event.inputs.deployToProd == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Prod Step
        run: echo "Deploying to Prod"
